### ISSUE TITLE
Why "Rule did not pass schema checks" message when I am creating a decision table?

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/rm-functions#10]
When I work on the decision table, I get a message that "Rule did not pass schema checks". It seems to be coming too early in the process, as I'm still creating a new rule -- I guess I'm being told there are still empty fields. There necessarily would be.

**Comment by RyanFleck** [comment]
The schema is checked every time part of the rule is saved to the "state" held in the react app or the "master" copy in the database.

What I need to fix here is the sliders at the bottom, where this originates:

![image](https://user-images.githubusercontent.com/28709508/97454975-f4a1c600-18fc-11eb-9d18-2f05dc8927d5.png)
