### ISSUE TITLE
Implement drop-down list for "Rule Group"

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/rm-functions#14]
"Rule Group" is right after "Output: Qualitative Weights"

Select the rule group that most applies:

Informal Custom or Preference
Operational Pattern
Formal Custom Without Legal Standing
Guideline, Instruction or Policy
Code of Conduct
Regulation or Directive
Common Law or Case Law
Statute or Legislation
International Law

**Comment by RyanFleck** [comment]
This has been implemented, closing.
