### ISSUE TITLE
Currently I can only get a maximum of 4 columns in the decision table. This must be unlimited (or max, say 30)

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/rm-functions#17]
I can add columns from 1 to 2, 3, 4 but then the + sign disappears.

**Comment by RyanFleck** [comment]
![image](https://user-images.githubusercontent.com/28709508/98752808-33656080-2380-11eb-9f73-7104663354a8.png)

@jpotvin the table was scrollable before, but has been extended to be the full page-width.

**Comment by RyanFleck** [comment]
![image](https://user-images.githubusercontent.com/28709508/98752923-6d366700-2380-11eb-8e94-46eec13da3fe.png)
