### ISSUE TITLE
Just a reminder that the (i) texts need completion (from the Guide to Field Names)

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/rm-functions#8]
The (i) sentences will be in addition to what is provided in the Guide to Field Names: https://docs.google.com/spreadsheets/d/1V76YYPWhiNy71pvgQsdJP5yaZoFArx_3vSSlTuCasOg/edit#gid=816716066

My intention was that the questions appearing in the Guide should serve as the field "labels", offering more a question-answer look.

**Comment by jpotvin** [comment]
This should be done asap.

**Comment by millenniallglyphs** [comment]
Many of these are not ready to be used as the label, such as "The 'manager' of a rule is considered to be the person most directly responsible for what this rule asserts."

**Comment by millenniallglyphs** [comment]
Closing since duplicate.
